### ISSUE TITLE
Bank xp

### ISSUE THREAD

**Issue by ed223** [urothis/nwn-module-DungeonEternalX#7]
Location: Bank
NPC: Bank Teller
Problem: Can't bank or donate xp, all he says "Silly customer, you cannot deposit your pocket lint"

**Comment by hotelechoxrayindiasierra** [comment]
This issue was fixed in Mav's most recent iteration of DeX... I feel like we should just use his last version of the Mod because it fixes a variety of issues which devs took a LOOONG time to remedy last time. Going through the time of fixing all this shit over again is a waste, and in doing so we're slowly but surely losing the confidence and patience of our player base.

**Comment by urothis** [comment]
741842cf70c23ceb0e8311d46365de53599bb887 corrects this issue. 
your opinion is... appreciated?
